### ISSUE TITLE
WITH dark reader extensions, Header text on hero not showing properly

### ISSUE THREAD

**Issue by foxane** [vespucchi/restaurant#1]
On the main page, background clip path is not showing properly, ONLY when using dark reader. 
I don't know if this a valid issue or not since the problem lies on dark reader. Tried on firefox and chrome, but the problem persist.

Anyway, your page looks awsome as hell!, keep it up my man 🤜

**Comment by ssimx** [comment]
Hey, thanks for the feedback. The issue was that I implemented h1 color as a linear gradient with the help of webkit-background-clip so that was causing dark reader to fail. I ditched that idea and set the color to plain white and now it's fixed.

Thank you I appreciate it, I try my best. Good luck with your projects :)
